// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "client.proto" (package "synaptica.client.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { SynapticaService } from "./client";
import type { ListGraphsResponse } from "./client";
import type { ListGraphsRequest } from "./client";
import type { GetMetricsResponse } from "./client";
import type { GetMetricsRequest } from "./client";
import type { DropIndexResponse } from "./client";
import type { DropIndexRequest } from "./client";
import type { CreateIndexResponse } from "./client";
import type { CreateIndexRequest } from "./client";
import type { ListIndexesResponse } from "./client";
import type { ListIndexesRequest } from "./client";
import type { GetSchemaResponse } from "./client";
import type { GetSchemaRequest } from "./client";
import type { ListLabelsResponse } from "./client";
import type { ListLabelsRequest } from "./client";
import type { ClusterStatusResponse } from "./client";
import type { ClusterStatusRequest } from "./client";
import type { HealthResponse } from "./client";
import type { HealthRequest } from "./client";
import type { RollbackTransactionResponse } from "./client";
import type { RollbackTransactionRequest } from "./client";
import type { CommitTransactionResponse } from "./client";
import type { CommitTransactionRequest } from "./client";
import type { BeginTransactionResponse } from "./client";
import type { BeginTransactionRequest } from "./client";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { QueryResponse } from "./client";
import type { QueryRequest } from "./client";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service synaptica.client.v1.SynapticaService
 */
export interface ISynapticaServiceClient {
    /**
     * Execute a GQL query and return results.
     *
     * @generated from protobuf rpc: ExecuteQuery
     */
    executeQuery(input: QueryRequest, options?: RpcOptions): UnaryCall<QueryRequest, QueryResponse>;
    /**
     * Execute a GQL query and stream results back.
     *
     * @generated from protobuf rpc: ExecuteQueryStream
     */
    executeQueryStream(input: QueryRequest, options?: RpcOptions): ServerStreamingCall<QueryRequest, QueryResponse>;
    /**
     * Begin an explicit transaction.
     *
     * @generated from protobuf rpc: BeginTransaction
     */
    beginTransaction(input: BeginTransactionRequest, options?: RpcOptions): UnaryCall<BeginTransactionRequest, BeginTransactionResponse>;
    /**
     * Commit an explicit transaction.
     *
     * @generated from protobuf rpc: CommitTransaction
     */
    commitTransaction(input: CommitTransactionRequest, options?: RpcOptions): UnaryCall<CommitTransactionRequest, CommitTransactionResponse>;
    /**
     * Rollback an explicit transaction.
     *
     * @generated from protobuf rpc: RollbackTransaction
     */
    rollbackTransaction(input: RollbackTransactionRequest, options?: RpcOptions): UnaryCall<RollbackTransactionRequest, RollbackTransactionResponse>;
    /**
     * Health check.
     *
     * @generated from protobuf rpc: Health
     */
    health(input: HealthRequest, options?: RpcOptions): UnaryCall<HealthRequest, HealthResponse>;
    /**
     * Get cluster status information.
     *
     * @generated from protobuf rpc: ClusterStatus
     */
    clusterStatus(input: ClusterStatusRequest, options?: RpcOptions): UnaryCall<ClusterStatusRequest, ClusterStatusResponse>;
    /**
     * List all node and edge labels with counts.
     *
     * @generated from protobuf rpc: ListLabels
     */
    listLabels(input: ListLabelsRequest, options?: RpcOptions): UnaryCall<ListLabelsRequest, ListLabelsResponse>;
    /**
     * Get schema information (labels + property keys).
     *
     * @generated from protobuf rpc: GetSchema
     */
    getSchema(input: GetSchemaRequest, options?: RpcOptions): UnaryCall<GetSchemaRequest, GetSchemaResponse>;
    /**
     * List secondary indexes.
     *
     * @generated from protobuf rpc: ListIndexes
     */
    listIndexes(input: ListIndexesRequest, options?: RpcOptions): UnaryCall<ListIndexesRequest, ListIndexesResponse>;
    /**
     * Create a secondary index.
     *
     * @generated from protobuf rpc: CreateIndex
     */
    createIndex(input: CreateIndexRequest, options?: RpcOptions): UnaryCall<CreateIndexRequest, CreateIndexResponse>;
    /**
     * Drop a secondary index.
     *
     * @generated from protobuf rpc: DropIndex
     */
    dropIndex(input: DropIndexRequest, options?: RpcOptions): UnaryCall<DropIndexRequest, DropIndexResponse>;
    /**
     * Get server metrics.
     *
     * @generated from protobuf rpc: GetMetrics
     */
    getMetrics(input: GetMetricsRequest, options?: RpcOptions): UnaryCall<GetMetricsRequest, GetMetricsResponse>;
    /**
     * List all available graphs.
     *
     * @generated from protobuf rpc: ListGraphs
     */
    listGraphs(input: ListGraphsRequest, options?: RpcOptions): UnaryCall<ListGraphsRequest, ListGraphsResponse>;
}
/**
 * @generated from protobuf service synaptica.client.v1.SynapticaService
 */
export class SynapticaServiceClient implements ISynapticaServiceClient, ServiceInfo {
    typeName = SynapticaService.typeName;
    methods = SynapticaService.methods;
    options = SynapticaService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Execute a GQL query and return results.
     *
     * @generated from protobuf rpc: ExecuteQuery
     */
    executeQuery(input: QueryRequest, options?: RpcOptions): UnaryCall<QueryRequest, QueryResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<QueryRequest, QueryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Execute a GQL query and stream results back.
     *
     * @generated from protobuf rpc: ExecuteQueryStream
     */
    executeQueryStream(input: QueryRequest, options?: RpcOptions): ServerStreamingCall<QueryRequest, QueryResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<QueryRequest, QueryResponse>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * Begin an explicit transaction.
     *
     * @generated from protobuf rpc: BeginTransaction
     */
    beginTransaction(input: BeginTransactionRequest, options?: RpcOptions): UnaryCall<BeginTransactionRequest, BeginTransactionResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<BeginTransactionRequest, BeginTransactionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Commit an explicit transaction.
     *
     * @generated from protobuf rpc: CommitTransaction
     */
    commitTransaction(input: CommitTransactionRequest, options?: RpcOptions): UnaryCall<CommitTransactionRequest, CommitTransactionResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<CommitTransactionRequest, CommitTransactionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Rollback an explicit transaction.
     *
     * @generated from protobuf rpc: RollbackTransaction
     */
    rollbackTransaction(input: RollbackTransactionRequest, options?: RpcOptions): UnaryCall<RollbackTransactionRequest, RollbackTransactionResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<RollbackTransactionRequest, RollbackTransactionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Health check.
     *
     * @generated from protobuf rpc: Health
     */
    health(input: HealthRequest, options?: RpcOptions): UnaryCall<HealthRequest, HealthResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<HealthRequest, HealthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get cluster status information.
     *
     * @generated from protobuf rpc: ClusterStatus
     */
    clusterStatus(input: ClusterStatusRequest, options?: RpcOptions): UnaryCall<ClusterStatusRequest, ClusterStatusResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ClusterStatusRequest, ClusterStatusResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * List all node and edge labels with counts.
     *
     * @generated from protobuf rpc: ListLabels
     */
    listLabels(input: ListLabelsRequest, options?: RpcOptions): UnaryCall<ListLabelsRequest, ListLabelsResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListLabelsRequest, ListLabelsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get schema information (labels + property keys).
     *
     * @generated from protobuf rpc: GetSchema
     */
    getSchema(input: GetSchemaRequest, options?: RpcOptions): UnaryCall<GetSchemaRequest, GetSchemaResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSchemaRequest, GetSchemaResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * List secondary indexes.
     *
     * @generated from protobuf rpc: ListIndexes
     */
    listIndexes(input: ListIndexesRequest, options?: RpcOptions): UnaryCall<ListIndexesRequest, ListIndexesResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListIndexesRequest, ListIndexesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Create a secondary index.
     *
     * @generated from protobuf rpc: CreateIndex
     */
    createIndex(input: CreateIndexRequest, options?: RpcOptions): UnaryCall<CreateIndexRequest, CreateIndexResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateIndexRequest, CreateIndexResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Drop a secondary index.
     *
     * @generated from protobuf rpc: DropIndex
     */
    dropIndex(input: DropIndexRequest, options?: RpcOptions): UnaryCall<DropIndexRequest, DropIndexResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<DropIndexRequest, DropIndexResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get server metrics.
     *
     * @generated from protobuf rpc: GetMetrics
     */
    getMetrics(input: GetMetricsRequest, options?: RpcOptions): UnaryCall<GetMetricsRequest, GetMetricsResponse> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMetricsRequest, GetMetricsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * List all available graphs.
     *
     * @generated from protobuf rpc: ListGraphs
     */
    listGraphs(input: ListGraphsRequest, options?: RpcOptions): UnaryCall<ListGraphsRequest, ListGraphsResponse> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListGraphsRequest, ListGraphsResponse>("unary", this._transport, method, opt, input);
    }
}
